---
- name: Install HAProxy and Keepalived
  become: true
  apt:
    name:
      - haproxy
      - keepalived
    state: present
  when: ansible_os_family == "Debian"

- name: Create HAProxy configuration file
  become: true
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify: restart haproxy
  when: ansible_os_family == "Debian"

- name: Create Keepalived configuration file
  become: true
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart keepalived
  when: ansible_os_family == "Debian"

- name: Enable and start HAProxy service
  become: true
  service:
    name: haproxy
    enabled: yes
    state: started
  when: ansible_os_family == "Debian"

- name: Enable and start Keepalived service
  become: true
  service:
    name: keepalived
    enabled: yes
    state: started
  when: ansible_os_family == "Debian"
