---
nginx_namespace: default
nginx_deployment_name: nginx-deployment
nginx_service_name: nginx-service
nginx_replicas: 2
nginx_image: nginx:latest
nginx_container_port: 80
service_type: LoadBalancer # Or ClusterIP, NodePort