---
- name: Add the Cilium Helm repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
    state: present
  become: true

- name: Install/Upgrade Cilium
  kubernetes.core.helm:
    name: "{{ cilium_release_name }}"
    namespace: "{{ cilium_namespace }}"
    chart_ref: cilium/cilium
    chart_version: "{{ cilium_version }}"
    values: "{{ cilium_values }}"
    state: present
  become: true