---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - prereq
    - airgap
    - raspberrypi

- name: Setup K3S server
  hosts: server
  become: true
  roles:
    - k3s_server

- name: Setup K3S agent
  hosts: agent
  become: true
  roles:
    - k3s_agent

- name: Setup K3S user
  hosts: user
  become: true
  roles:
    - k3s_user

- name: Set up load balancer
  become: true
  hosts: k3s_cluster
  roles:
    - role: metallb
      when: load_balancer == 'metallb'
    - role: traefik
      when: load_balancer == 'traefik'
    - role: nginx
      when: load_balancer == 'nginx'
    - role: cillium
      when: load_balancer == 'cillium'
