---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - prereq
    - airgap
    - raspberrypi

- name: Setup K3S server
  hosts: server
  become: true
  roles:
    - k3s_server
    - haproxy

- name: Setup K3S agent
  hosts: agent
  become: true
  roles:
    - k3s_agent

#- name: Setup K3S User
#  hosts: user
#  become: true
#  roles:
#    - role: k3s_user
