---
- name: Reboot Pi
  ansible.builtin.reboot:
    msg: "Rebooting host to apply kernel changes"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

- name: Regenerate bootloader image
  ansible.builtin.command: ./mkscr
  args:
    chdir: /boot
  notify: Reboot Pi
  changed_when: true

